[build]
  command = "bundle exec jekyll build"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.2"
  JEKYLL_ENV = "production"

[context.production]
  command = "bundle exec jekyll build"

[context.deploy-preview]
  command = "bundle exec jekyll build --future"

[context.branch-deploy]
  command = "bundle exec jekyll build --future"
